
name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build-mac-linux:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v10
    - name: Test
      run: sbt compile test

  # scala-native doesn't support windows yet
  # build-windows:

  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [windows-latest]

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #   - name: Configure git
  #     run: "git config --global core.autocrlf false"
  #     shell: bash
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - uses: olafurpg/setup-scala@v10
  #   - name: Test
  #     shell: bash
  #     run: sbt compile test
