
name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:

    - name: Configure git
      run: "git config --global core.autocrlf false"
      shell: bash
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Checkout
      uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v10
    - name: Test
      shell: bash
      run: sbt compile test nativeImage

  document:

    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}

    steps:

    - name: Checkout
      uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v10
    - name: Prepare snapshot documentation branch
      run: "git checkout -B snapshot-docs && git reset --hard main"
    - name: Generate docs
      run: sbt "genDocs"
    - name: Commit the new docs
      run: |
        git config --local user.email "${{ github.event.pusher.email }}"
        git config --local user.name "${{ github.event.pusher.name }}"
        git add . && git commit -m "Generate snapshot docs" #&& git push --force
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: snapshot-docs
        force: true
