
name: CI

on:
  push:
    branches:
      - '*'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:

    - name: Configure git
      run: "git config --global core.autocrlf false"
      shell: bash
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Checkout
      uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v10
    - name: Test
      shell: bash
      run: sbt compile test nativeImage
