name: Publish

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  publish-github:
    name: Publish to GitHub release for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: scala-app-template
            asset_name: scala-app-template-linux-amd64
          - os: windows-latest
            artifact_name: scala-app-template.exe
            asset_name: scala-app-template-windows-amd64.exe
          - os: macos-latest
            artifact_name: scala-app-template
            asset_name: scala-app-template-macos-amd64

    steps:
    - name: Configure git
      run: "git config --global core.autocrlf false"
      shell: bash
    - uses: ilammy/msvc-dev-cmd@v1
    - uses: olafurpg/setup-scala@v10
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build release
      shell: bash
      run: sbt nativeImage
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/native-image/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}

  once:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - id: install-secret-key
      name: Install gpg secret key
      run: |
        cat <(echo -e "${{ secrets.MAVEN_CENTRAL_GPG_PRIVATE_KEY_B64 }}") | base64 --decode | gpg --batch --import
        gpg --list-keys
    - name: Publish to maven central
      env:
        MAVEN_CENTRAL_GPG_PRIVATE_KEY_ID: ${{ secrets.MAVEN_CENTRAL_GPG_PRIVATE_KEY_ID }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        PGP_PASSPHRASE: ${{ secrets.MAVEN_CENTRAL_GPG_PASSWORD }}
      run: sbt publishSigned sonatypeRelease
    - name: Publish to bintray
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_PASS: ${{ secrets.BINTRAY_PASS }}
      run: sbt "set publishTo := (publishTo in bintray).value"  publish
